// Stage claat static assets into public/ so the embedded codelab HTML can
// resolve its relative references at the deployed URLs:
//
//   page:  /jumpstarts/<slug>/            (generated by [...slug].astro)
//   css/js: ../assets/*   -> /jumpstarts/assets/*
//   images: img/*         -> /jumpstarts/<slug>/img/*
//
// The lab sources live in ./jumpstarts (the content root, NOT served by Astro).
// Astro only ships files under ./public, so we link them in. We use symlinks so
// the ~90MB of images are not physically duplicated in the working tree; Vite
// dereferences them when copying public/ into dist/, so the real files still
// land in the final build output.
//
// public/jumpstarts/ is generated and git-ignored — run this before dev/build
// (wired into the npm "dev" and "build" scripts).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(root, 'jumpstarts');
const DEST = path.join(root, 'public', 'jumpstarts');

/** Replace whatever is at `link` with a symlink to `target`. */
function link(target, linkPath) {
  fs.mkdirSync(path.dirname(linkPath), { recursive: true });
  try {
    fs.rmSync(linkPath, { recursive: true, force: true });
  } catch {
    /* nothing there yet */
  }
  // 'junction' is ignored on POSIX and helps on Windows for directories.
  fs.symlinkSync(target, linkPath, 'dir');
}

// Wipe and recreate the staged tree so removed labs don't linger.
fs.rmSync(DEST, { recursive: true, force: true });
fs.mkdirSync(DEST, { recursive: true });

// Shared claat runtime (codelab-elements.js/css, prettify, shims).
const assets = path.join(SRC, 'assets');
if (fs.existsSync(assets)) link(assets, path.join(DEST, 'assets'));

// Per-lab image folders.
let labs = 0;
for (const entry of fs.readdirSync(SRC, { withFileTypes: true })) {
  if (!entry.isDirectory() || entry.name === 'assets') continue;
  const img = path.join(SRC, entry.name, 'img');
  if (fs.existsSync(img)) {
    link(img, path.join(DEST, entry.name, 'img'));
    labs++;
  }
}

console.log(`[stage-claat] linked assets + img/ for ${labs} labs into public/jumpstarts/`);
